version: "3"
services:
  server:
    build: server
    container_name: lost-server
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
    volumes:
      - ./server/:/server
  client:
    build: client
    container_name: lost-client
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
