version: "3"
services:
  server:
    build: server
    container_name: lost-server
    stdin_open: true
    tty: true
    ports:
      - 5003:5000
    volumes:
      - ./server/:/app
  client:
    build: client
    container_name: lost-client
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    ports:
      - 3003:3000
    volumes:
      - ./client:/app
