import _ from 'lodash'

const itemsObj = {
  '14844': {name: 'Apple Full Cooked', single: false},
  '40010': {name: 'Apple Full Ripe', single: false},
  '2000': {name: 'Apple Half Cooked', single: false},
  '7278': {name: 'Apple Half Ripe', single: false},
  '56460': {name: 'Arrow (Rusty)', single: false},
  '29772': {name: 'Arrow Shaft Wooden', single: false},
  '47468': {name: 'Blueberry Full Cooked', single: false},
  '45012': {name: 'Blueberry Full Ripe', single: false},
  '56546': {name: 'Bow', single: true},
  '60742': {name: 'Carrot Full Cooked', single: false},
  '58838': {name: 'Carrot Full Ripe', single: false},
  '63758': {name: 'Carrot Half Cooked', single: false},
  '63354': {name: 'Carrot Half Ripe', single: false},
  '45082': {name: 'Cauldron Medium', single: true},
  '30164': {name: 'Chocolate Easter Egg', single: false},
  '19658': {name: 'Coal', single: false},
  '32850': {name: 'Copper Ingot', single: false},
  '2484': {name: 'Copper Ore', single: false},
  '8002': {name: 'Crystal Gem Blue', single: false},
  '23400': {name: 'Crystal Lance Blue', single: true},
  '2924': {name: 'Crystal Pick Blue', single: true},
  '7092': {name: 'Crystal Shard Blue', single: false},
  '56894': {name: 'Crystal Sword Blue', single: true},
  '31326': {name: 'Dynamite', single: false},
  '54506': {name: 'Eggplant Full Cooked', single: false},
  '53982': {name: 'Eggplant Full Ripe', single: false},
  '62142': {name: 'Eggplant Half Cooked', single: false},
  '61738': {name: 'Eggplant Half Ripe', single: false},
  '13158': {name: 'Electrum Ingot', single: false},
  '39484': {name: 'Flint', single: false},
  '52530': {name: 'Garlic Full Cooked', single: false},
  '52126': {name: 'Garlic Full Ripe', single: false},
  '60526': {name: 'Garlic Half Cooked', single: false},
  '60122': {name: 'Garlic Half Ripe', single: false},
  '59336': {name: 'Geode', single: false},
  '29678': {name: 'Geode Half 01', single: false},
  '38512': {name: 'Geode Half 02', single: false},
  '30092': {name: 'Gold Ingot', single: false},
  '61650': {name: 'Gold Ore', single: false},
  '61648': {name: 'GoldCoin', single: false},
  '29032': {name: 'Gourd Canteen', single: true},
  '57872': {name: 'Grass Clump', single: false},
  '3506': {name: 'Handle Wood Round Fist', single: true},
  '42230': {name: 'Handle Wood XS', single: true},
  '59588': {name: 'Handle Wood S', single: true},
  '44204': {name: 'Handle Wood M', single: true},
  '44066': {name: 'Handle Wood L', single: true},
  '61400': {name: 'Handle Wood M Branch', single: true},
  '61098': {name: 'Handle Wood L Branch', single: true},
  '64172': {name: 'Handle Wood Curled', single: true},
  '57838': {name: 'Handle Wood Tonfa', single: true},
  '64410': {name: 'Handle Wood Bow', single: true},
  '22988': {name: 'Handle Metal Fist', single: true},
  '34898': {name: 'Handle Metal XS, No Pommel', single: true},
  '28636': {name: 'Handle Metal XS, S Pommel', single: true},
  '5920': {name: 'Handle Metal XS, L Pommel', single: true},
  '19316': {name: 'Handle Metal Thick (L Swords)', single: true},
  '61856': {name: 'Handle Metal M', single: true},
  '25290': {name: 'Handle Metal L', single: true},
  '23012': {name: 'Iron Ingot', single: false},
  '61652': {name: 'Iron Ore', single: false},
  '960': {name: 'Ka Karimata Arrow (Hebios Arrow)', single: false},
  '34994': {name: 'Katana', single: true},
  '32002': {name: 'Kunai', single: false},
  '41760': {name: 'Lantern', single: true},
  '55914': {name: 'Large Spiked Wooden Club', single: true},
  '25100': {name: 'Metal Bow', single: true},
  '46510': {name: 'MushroomBrown Full Cooked', single: false},
  '61666': {name: 'MushroomBrown Full Ripe', single: false},
  '50916': {name: 'MushroomBrown Half Cooked', single: false},
  '48460': {name: 'MushroomBrown Half Ripe', single: false},
  '9414': {name: 'MushroomCaveLarge Half Cooked', single: false},
  '54182': {name: 'MushroomCaveLarge Half Ripe', single: false},
  '40066': {name: 'MushroomCaveSmall Full Cooked', single: false},
  '58270': {name: 'MushroomCaveSmall Full Ripe', single: false},
  '44488': {name: 'MushroomCaveSmall Half Cooked', single: false},
  '41834': {name: 'MushroomCaveSmall Half Ripe', single: false},
  '41428': {name: 'MushroomGlowing Full Cooked', single: false},
  '38966': {name: 'MushroomGlowing Full Ripe', single: false},
  '34042': {name: 'MushroomGlowing Half Cooked', single: false},
  '31580': {name: 'MushroomGlowing Half Ripe', single: false},
  '46888': {name: 'MushroomRed Full Cooked', single: false},
  '61658': {name: 'MushroomRed Full Ripe', single: false},
  '40816': {name: 'MushroomRed Half Cooked', single: false},
  '38360': {name: 'MushroomRed Half Ripe', single: false},
  '24774': {name: 'Mythril Ingot', single: false},
  '11702': {name: 'Mythril Ore', single: false},
  '41052': {name: 'Naginata (Hebios Spear)', single: true},
  '48214': {name: 'Onion Full Cooked', single: false},
  '47730': {name: 'Onion Full Ripe', single: false},
  '59314': {name: 'Onion Half Burnt', single: false},
  '58910': {name: 'Onion Half Cooked', single: false},
  '58506': {name: 'Onion Half Ripe', single: false},
  '60868': {name: 'Palladium Ingot', single: false},
  '57840': {name: 'Potato Full Cooked', single: false},
  '54692': {name: 'Potato Full Ripe', single: false},
  '50612': {name: 'Potato Half Cooked', single: false},
  '48134': {name: 'Potato Half Ripe', single: false},
  '5010': {name: 'pumpkin full cooked', single: true},
  '4488': {name: 'pumpkin full ripe', single: true},
  '3082': {name: 'pumpkin half cooked', single: false},
  '2720': {name: 'pumpkin half ripe', single: false},
  '41930': {name: 'pumpkin piece cooked', single: false},
  '64640': {name: 'Quiver', single: true},
  '31034': {name: 'Red Iron Ingot', single: false},
  '4412': {name: 'Rusty Axe', single: true},
  '40366': {name: 'Rusty Chisel', single: true},
  '29296': {name: 'Rusty Greataxe', single: true},
  '63156': {name: 'Rusty Greatsword', single: true},
  '36126': {name: 'Rusty Hammer', single: true},
  '46874': {name: 'Rusty Pickaxe', single: true},
  '44824': {name: 'Rusty Short Sword', single: true},
  '27038': {name: 'Sai (Hebios)', single: true},
  '49578': {name: 'Salt', single: false},
  '55930': {name: 'Sandstone Stone', single: false},
  '53576': {name: 'Schmeechee Glowing', single: true},
  '63728': {name: 'Schmeechee Orange', single: true},
  '31646': {name: 'Schmeechee Poisonous', single: true},
  '3532': {name: 'Schmeechee Red', single: true},
  '23528': {name: 'Silver Ingot', single: false},
  '9586': {name: 'Silver Ore', single: false},
  '7918': {name: 'Spriggull Feather Blue', single: false},
  '18734': {name: 'Spriggull Feather Red', single: false},
  '24406': {name: 'SpriggullDrumstick Bone', single: false},
  '33190': {name: 'SpriggullDrumstick Full Cooked', single: false},
  '43430': {name: 'SpriggullDrumstick Full Ripe', single: false},
  '8440': {name: 'SpriggullDrumstick Half Cooked', single: false},
  '5972': {name: 'SpriggullDrumstick Half Ripe', single: false},
  '5170': {name: 'SpyGlass', single: true},
  '61674': {name: 'Stick', single: false},
  '61670': {name: 'Stone', single: false},
  '33542': {name: 'Teleport Point', single: true},
  '38098': {name: 'Tomato Full Cooked', single: false},
  '37454': {name: 'Tomato Full Ripe', single: false},
  '57294': {name: 'Tomato Half Cooked', single: false},
  '56890': {name: 'Tomato Half Ripe', single: false},
  '32198': {name: 'Valyan Ingot', single: false},
  '16464': {name: 'Viridium Ingot', single: false},
  '29856': {name: 'Wakizashi (Hebios Shortsword)', single: true},
  '47118': {name: 'Wood Wedge', single: false},
  '25908': {name: 'Wooden Bowl', single: false},
  '63904': {name: 'Wooden Bucket', single: true},
  '45608': {name: 'Wooden Dice', single: true},
  '15274': {name: 'Wooden Ladle', single: true},
  '16448': {name: 'Wooden Short Sword', single: true},
  '17262': {name: 'Wooden Stake', single: false}
}

const itemsObjArchive = {
  '17258': {name: 'Brown Mushroom Shield', single: true},
  '27314': {name: 'Candy Cane', single: false},
  '7676': {name: 'Candy Cane Knife', single: false},
  '27006': {name: 'Chestplate_leatherArmor (Pickup)', single: false},
  '41410': {name: 'ChestPlate_metalArmor (Pickup)', single: false},
  '15152': {name: 'ChestPlate_WyrmArmor (Pickup)', single: false},
  '55462': {name: 'Easter Egg 01 (Blue)', single: false},
  '57998': {name: 'Easter Egg 02 (Gold)', single: false},
  '20128': {name: 'Easter Egg 03 (Purple)', single: false},
  '21558': {name: 'Easter Egg 04 (Red)', single: false},
  '60808': {name: 'helmet_bowletCap (Pickup)', single: true},
  '146': {name: 'helmet_cowboyHat (Pickup)', single: true},
  '4780': {name: 'helmet_farmingCap (Pickup)', single: true},
  '13562': {name: 'helmet_farmingCapFrayed (Pickup)', single: true},
  '39512': {name: 'helmet_gotera (Pickup)', single: true},
  '16434': {name: 'Helmet_leatherArmor (Pickup)', single: true},
  '40796': {name: 'Helmet_metalArmor (Pickup)', single: true},
  '29514': {name: 'helmet_mushroom_brown (Pickup)', single: true},
  '23312': {name: 'helmet_mushroom_glowing (Pickup)', single: true},
  '44756': {name: 'helmet_mushroom_red (Pickup)', single: true},
  '9146': {name: 'helmet_newsboyCap (Pickup)', single: true},
  '54778': {name: 'Helmet_Santa_hat (Pickup)', single: true},
  '64476': {name: 'Helmet_WyrmArmor (Pickup)', single: true},
  '54302': {name: 'LeftGauntlet_leatherArmor (Pickup)', single: true},
  '39242': {name: 'LeftGauntlet_metalArmor (Pickup)', single: true},
  '44378': {name: 'LeftGauntlet_WyrmArmor_L (Pickup)', single: true},
  '31100': {name: 'LeftShoulderPad_leatherArmor (Pickup)', single: true},
  '47766': {name: 'LeftShoulderPad_metalArmor (Pickup)', single: true},
  '65134': {name: 'LeftShoulderPad_WyrmArmor_L (Pickup)', single: true},
  '17088': {name: 'LeftTasset_leatherArmor (Pickup)', single: true},
  '48422': {name: 'LeftTasset_metalArmor (Pickup)', single: true},
  '37828': {name: 'LeftTasset_WyrmArmor_L (Pickup)', single: true},
  '49188': {name: 'Red Mushroom Shield', single: true},
  '57608': {name: 'RightGauntlet_leatherArmor (Pickup)', single: true},
  '46062': {name: 'RightGauntlet_metalArmor (Pickup)', single: true},
  '34934': {name: 'RightGauntlet_WyrmArmor_R (Pickup)', single: true},
  '20328': {name: 'RightShoulderPad_leatherArmor (Pickup)', single: true},
  '47024': {name: 'RightShoulderPad_metalArmor (Pickup)', single: true},
  '54136': {name: 'RightShoulderPad_WyrmArmor_R (Pickup)', single: true},
  '27860': {name: 'RightTasset_leatherArmor (Pickup)', single: true},
  '42054': {name: 'RightTasset_metalArmor (Pickup)', single: true},
  '46034': {name: 'RightTasset_WyrmArmor_R (Pickup)', single: true},
  '20684': {name: 'Rusty Shield', single: true},
}

const sortFn = (a, b) => a[1].name === b[1].name ? 0 : (a[1].name < b[1].name ? -1 : 1)
const itemsArr = _.toPairs(itemsObj).sort(sortFn)

export  {itemsObj, itemsArr, itemsObjArchive}
